version: "2.0"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=develop
      - DB_PORT=27017
      - DB_NAME=my-app
      - PORT=8080
    entrypoint:
      - npm
      - start
  database:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
